id = "cucumber"
name = "Cucumber/Gherkin support"
version = "0.0.2"
schema_version = 1
authors = ["Thomas Liebeskind <thomas.liebeskind@gmail.com>"]
description = "Zed Cucumber Support"
repository = "https://github.com/thlcodes/zed-extension-cucumber"

[language_servers.cucumber]
name = "Cucumber LSP"
language = "Gherkin"

[grammars.gherkin]
repository = "https://github.com/thlcodes/tree-sitter-gherkin"
commit = "133e9b270e80ecb8875bbe2f0625fcb276ea5ddb"
